name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build-test:
    name: Build and test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Env
        run: |
          echo "RUSTFLAGS=-Dwarnings" >> $GITHUB_ENV
          echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
          echo "RUST_LOG=info" >> $GITHUB_ENV

      - name: Format (rustfmt)
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets -- -D warnings

      - name: Build (release)
        run: cargo build --release

      - name: Tests (Ubuntu full)
        if: matrix.os == 'ubuntu-latest'
        run: cargo test --all --release -- --test-threads=1

      - name: Tests (Windows smoke)
        if: matrix.os == 'windows-latest'
        run: |
          cargo test --test typed_errors --test ast_limits --release

      - name: Docs pointers
        run: |
          echo "AST Sentinel documentation links:"
          echo " - Project overview: README.md"
          echo " - Hooks reference: README_HOOKS.md"
          echo " - Project structure: docs/PROJECT_STRUCTURE.md"
          echo " - Testing guide: docs/TESTING.md"
