name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo build
        run: cargo build --features ast_fastpath --locked
      - name: Cargo test (fastpath)
        run: cargo test --features ast_fastpath --locked
      - name: Cargo test (legacy)
        run: cargo test --no-default-features --locked
      - name: Install tarpaulin
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -LsSf https://github.com/xd009642/tarpaulin/releases/latest/download/cargo-tarpaulin-x86_64-unknown-linux-gnu.tar.gz -o tarpaulin.tgz || exit 0
          [ -f tarpaulin.tgz ] && sudo tar -xzf tarpaulin.tgz -C /usr/local/bin || true
      - name: Coverage gate (fail under 80%)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo tarpaulin --features ast_fastpath --timeout 120 --fail-under 80 --out Xml
      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest' && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: cobertura.xml
